# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'dotenv', '~> 2.7'
gem 'dry-system', '~> 0.18'
gem 'pry', '~> 0.13'
gem 'rake', '~> 13.0'
gem 'zeitwerk'

group :development do
  gem 'rubocop', '~> 1.6'
  gem 'rubocop-rake', '~> 0.5'
  gem 'rubocop-rspec', '~> 2.1'
end

group :test do
  gem 'rspec', '~> 3.0'
end
