# frozen_string_literal: true

require 'dotenv/load'
require_relative 'system/boot'

begin
  require 'rspec/core/rake_task'
  RSpec::Core::RakeTask.new(:spec)
rescue LoadError
  # just ignore
end

begin
  require 'rubocop/rake_task'
  RuboCop::RakeTask.new
rescue LoadError
  # nil
end
